lista_pessoas = [
    {"nome": "Ana", "sexo": "Feminino"},
    {"nome": "João", "sexo": "Masculino"},
    {"nome": "Maria", "sexo": "Feminino"},
    {"nome": "Pedro", "sexo": "Masculino"},
    {"nome": "Sofia", "sexo": "Feminino"},
    {"nome": "Carlos", "sexo": "Masculino"},
    {"nome": "Laura", "sexo": "Feminino"},
    {"nome": "Gabriel", "sexo": "Masculino"},
    {"nome": "Beatriz", "sexo": "Feminino"},
    {"nome": "Lucas", "sexo": "Masculino"},
    {"nome": "Camila", "sexo": "Feminino"},
    {"nome": "Matheus", "sexo": "Masculino"},
    {"nome": "Juliana", "sexo": "Feminino"},
    {"nome": "Rafael", "sexo": "Masculino"},
    {"nome": "Isabela", "sexo": "Feminino"},
    {"nome": "Leonardo", "sexo": "Masculino"},
    {"nome": "Bruna", "sexo": "Feminino"},
    {"nome": "Guilherme", "sexo": "Masculino"},
    {"nome": "Fernanda", "sexo": "Feminino"},
    {"nome": "André", "sexo": "Masculino"},
    {"nome": "Paula", "sexo": "Feminino"},
    {"nome": "Felipe", "sexo": "Masculino"},
    {"nome": "Larissa", "sexo": "Feminino"},
    {"nome": "Thiago", "sexo": "Masculino"},
    {"nome": "Luiza", "sexo": "Feminino"},
    {"nome": "Alexandre", "sexo": "Masculino"},
    {"nome": "Mariana", "sexo": "Feminino"},
    {"nome": "Gustavo", "sexo": "Masculino"},
    {"nome": "Vitória", "sexo": "Feminino"},
    {"nome": "Eduardo", "sexo": "Masculino"},
    {"nome": "Giovanna", "sexo": "Feminino"},
    {"nome": "Rodrigo", "sexo": "Masculino"},
    {"nome": "Carolina", "sexo": "Feminino"},
    {"nome": "Daniel", "sexo": "Masculino"},
    {"nome": "Gabriela", "sexo": "Feminino"},
    {"nome": "Lucas", "sexo": "Masculino"},
    {"nome": "Renata", "sexo": "Feminino"},
    {"nome": "Victor", "sexo": "Masculino"},
    {"nome": "Vanessa", "sexo": "Feminino"},
    {"nome": "Marcos", "sexo": "Masculino"},
    {"nome": "Raquel", "sexo": "Feminino"},
    {"nome": "Rafael", "sexo": "Masculino"},
    {"nome": "Letícia", "sexo": "Feminino"},
    {"nome": "André", "sexo": "Masculino"},
    {"nome": "Amanda", "sexo": "Feminino"},
    {"nome": "Gustavo", "sexo": "Masculino"},
    {"nome": "Fernanda", "sexo": "Feminino"},
    {"nome": "Matheus", "sexo": "Masculino"},
    {"nome": "Natália", "sexo": "Feminino"},
    {"nome": "Bruno", "sexo": "Masculino"},
    {"nome": "Júlia", "sexo": "Feminino"},
    {"nome": "Lucas", "sexo": "Masculino"},
    {"nome": "Giovanna", "sexo": "Feminino"},
    {"nome": "Guilherme", "sexo": "Masculino"},
    {"nome": "Mariana", "sexo": "Feminino"},
    {"nome": "Felipe", "sexo": "Masculino"},
    {"nome": "Isabela", "sexo": "Feminino"},
    {"nome": "Pedro", "sexo": "Masculino"},
    {"nome": "Beatriz", "sexo": "Feminino"},
    {"nome": "Thiago", "sexo": "Masculino"},
    {"nome": "Camila", "sexo": "Feminino"},
    {"nome": "Gabriel", "sexo": "Masculino"},
    {"nome": "Laura", "sexo": "Feminino"},
    {"nome": "Leonardo", "sexo": "Masculino"},
    {"nome": "Luiza", "sexo": "Feminino"},
    {"nome": "Carlos", "sexo": "Masculino"},
    {"nome": "Juliana", "sexo": "Feminino"},
    {"nome": "Eduardo", "sexo": "Masculino"},
    {"nome": "Bruna", "sexo": "Feminino"},
    {"nome": "André", "sexo": "Masculino"},
    {"nome": "Larissa", "sexo": "Feminino"},
    {"nome": "Rafael", "sexo": "Masculino"},
    {"nome": "Fernanda", "sexo": "Feminino"},
    {"nome": "Gustavo", "sexo": "Masculino"},
    {"nome": "Vanessa", "sexo": "Feminino"},
    {"nome": "Matheus", "sexo": "Masculino"},
    {"nome": "Renata", "sexo": "Feminino"},
    {"nome": "Victor", "sexo": "Masculino"},
    {"nome": "Amanda", "sexo": "Feminino"},
    {"nome": "Marcos", "sexo": "Masculino"},
    {"nome": "Letícia", "sexo": "Feminino"},
    {"nome": "Daniel", "sexo": "Masculino"},
    {"nome": "Natália", "sexo": "Feminino"},
    {"nome": "Lucas", "sexo": "Masculino"},
    {"nome": "Raquel", "sexo": "Feminino"},
    {"nome": "André", "sexo": "Masculino"},
    {"nome": "Carolina", "sexo": "Feminino"},
    {"nome": "Rafael", "sexo": "Masculino"},
    {"nome": "Giovanna", "sexo": "Feminino"},
    {"nome": "Gustavo", "sexo": "Masculino"},
    {"nome": "Gabriel", "sexo": "Masculino"},
    {"nome": "Isabela", "sexo": "Feminino"},
    {"nome": "Pedro", "sexo": "Masculino"},
    {"nome": "Beatriz", "sexo": "Feminino"},
    {"nome": "Thiago", "sexo": "Masculino"},
    {"nome": "Camila", "sexo": "Feminino"},
    {"nome": "Lucas", "sexo": "Masculino"},
    {"nome": "Giovanna", "sexo": "Feminino"},
    {"nome": "Guilherme", "sexo": "Masculino"},
    {"nome": "Mariana", "sexo": "Feminino"},
    {"nome": "Felipe", "sexo": "Masculino"},
    {"nome": "Isabela", "sexo": "Feminino"},
    {"nome": "Pedro", "sexo": "Masculino"},
    {"nome": "Beatriz", "sexo": "Feminino"},
    {"nome": "Thiago", "sexo": "Masculino"},
    {"nome": "Camila", "sexo": "Feminino"},
    {"nome": "Gabriel", "sexo": "Masculino"},
    {"nome": "Laura", "sexo": "Feminino"},
    {"nome": "Leonardo", "sexo": "Masculino"},
    {"nome": "Luiza", "sexo": "Feminino"},
    {"nome": "Carlos", "sexo": "Masculino"},
    {"nome": "Juliana", "sexo": "Feminino"},
    {"nome": "Eduardo", "sexo": "Masculino"},
    {"nome": "Bruna", "sexo": "Feminino"},
    {"nome": "André", "sexo": "Masculino"},
    {"nome": "Larissa", "sexo": "Feminino"},
    {"nome": "Rafael", "sexo": "Masculino"},
    {"nome": "Fernanda", "sexo": "Feminino"},
    {"nome": "Gustavo", "sexo": "Masculino"},
    {"nome": "Vanessa", "sexo": "Feminino"},
    {"nome": "Matheus", "sexo": "Masculino"},
    {"nome": "Renata", "sexo": "Feminino"},
    {"nome": "Victor", "sexo": "Masculino"},
    {"nome": "Amanda", "sexo": "Feminino"},
    {"nome": "Marcos", "sexo": "Masculino"},
    {"nome": "Letícia", "sexo": "Feminino"},
    {"nome": "Daniel", "sexo": "Masculino"},
    {"nome": "Natália", "sexo": "Feminino"},
    {"nome": "Lucas", "sexo": "Masculino"},
    {"nome": "Raquel", "sexo": "Feminino"},
    {"nome": "André", "sexo": "Masculino"},
    {"nome": "Carolina", "sexo": "Feminino"},
    {"nome": "Rafael", "sexo": "Masculino"},
    {"nome": "Giovanna", "sexo": "Feminino"},
    {"nome": "Gustavo", "sexo": "Masculino"},
    {"nome": "Júlia", "sexo": "Feminino"}
]

locais_ficticios = [
    "Cidadela das Sombras",
    "Vale Encantado",
    "Pico da Serenidade",
    "Floresta Esmeralda",
    "Ilha dos Sonhos",
    "Montanha Nebulosa",
    "Caverna dos Mistérios",
    "Deserto Proibido",
    "Lago da Serpente",
    "Vila dos Espíritos"
]

def calcular_soma(dicionario):
    soma = 0

    for valor in dicionario.values():
        if isinstance(valor, dict):
            soma += calcular_soma(valor)
        else:
            soma += valor

    return soma